const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=path.resolve(__dirname,'..'),base=process.env.TKB_BASE||'http://127.0.0.1:8796',KEY='smart_tkb_thcs_v3_1_2_session_candidate';
(async()=>{const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']}),p=await b.newPage(),checks=[],errors=[];const ok=t=>{checks.push(t);console.log('PASS',t);};p.on('pageerror',e=>errors.push(e.message));
try{
 await p.goto(base);await p.waitForFunction(()=>document.querySelector('#nc').textContent==='9');await p.waitForFunction(()=>document.querySelector('#day-count').textContent.includes('369'));
 assert.equal(await p.locator('[data-slot-day]').count(),41);assert.equal(await p.locator('[data-slot-day="1"][data-slot-shift="pm"]').count(),0);assert.equal(await p.locator('[data-slot-day="5"][data-slot-shift="am"]').count(),4);assert((await p.locator('#grid').textContent()).includes('NGHỈ'));ok('Reference exactly41actualslots,9sessions; TueThuSat afternoons closed; SatAM4');
 const input=(d,sh)=>p.locator(`[data-session-day="${d}"][data-session-shift="${sh}"]`),change=async(d,sh,n)=>{await input(d,sh).fill(String(n));await input(d,sh).dispatchEvent('change');};
 for(let n=0;n<=5;n++){await change(0,'am',n);assert.equal(await p.locator('[data-slot-day="0"][data-slot-shift="am"]').count(),n);}ok('Selecting0..5creates exact cells only1..N');
 await change(0,'pm',0);await change(0,'am',0);assert.equal(await p.locator('[data-slot-day="0"]').count(),0);assert.equal(await p.locator('[data-rest-day="0"]').count(),2);ok('Entire day0renders NGHI and no slots');
 await p.locator('#reference-calendar').click();await p.locator('#session-scope').selectOption('C08A01');await change(0,'am',2);await p.locator('#copy-from').selectOption('C08A01');await p.locator('#copy-to').selectOption('C08A02');await p.locator('#copy-calendar').click();await p.locator('#session-scope').selectOption('C08A02');assert.equal(await input(0,'am').inputValue(),'2');await p.locator('#session-scope').selectOption('C08A03');assert.equal(await input(0,'am').inputValue(),'5');ok('Per-class override and copy affect selectedclasses only');
 await p.locator('#viewer').selectOption('C08A02');assert.equal(await p.locator('[data-slot-day="0"][data-slot-shift="am"]').count(),2);await p.locator('#session-scope').selectOption('C08A02');await p.locator('#inherit-grade').click();assert.equal(await input(0,'am').inputValue(),'5');ok('Classviewer honors own calendar; reset uses gradecalendar');
 await p.locator('#session-scope').selectOption('C08A01');await p.locator('#apply-grade').click();await p.locator('#session-scope').selectOption('C08A03');assert.equal(await input(0,'am').inputValue(),'2');ok('Applygrade copies exact displayedcalendar to all selectedclasses');
 await p.locator('#save-calendar').click();await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('Đã lưu cấu hình'));await change(0,'am',4);await p.locator('#restore-calendar').click();await p.waitForFunction(()=>document.querySelector('[data-session-day="0"][data-session-shift="am"]').value==='2');await p.reload();await p.waitForFunction(()=>document.querySelector('#nc').textContent==='9');assert.equal(await input(0,'am').inputValue(),'2');ok('Save/restore/reload preserve counts including zeros');
 let dl=p.waitForEvent('download');await p.locator('#download-calendar').click();await (await dl).saveAs(R+'/reports/SESSION_CALENDAR_EXPORT.json');const good=JSON.parse(fs.readFileSync(R+'/reports/SESSION_CALENDAR_EXPORT.json'));const bad=structuredClone(good);bad.session_config.week[0].am=-1;await p.locator('#calendar-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('Số tiết'));assert.equal(await input(0,'am').inputValue(),'2');await p.locator('#calendar-file').setInputFiles(R+'/reports/SESSION_CALENDAR_EXPORT.json');ok('Calendar JSON download/import; malformed import atomic');
 await p.locator('#reference-calendar').click();await p.locator('#include-sunday').check();assert.equal(await p.locator('[data-session-day]').count(),14);await change(6,'am',1);assert.equal(await p.locator('[data-slot-day="6"][data-slot-shift="am"]').count(),1);await p.locator('#include-sunday').click();await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('Đặt hai buổi'));assert(await p.locator('#include-sunday').isChecked());await change(6,'am',0);await p.locator('#include-sunday').uncheck();ok('OptionalSunday defaults0; cannot silentlyerase chosenSunday count');
 await p.locator('[data-tab="data"]').click();await p.locator('#json').setInputFiles(R+'/tests/GRADE8_BROWSER_FIXTURE.json');await p.waitForFunction(()=>document.querySelector('#nc').textContent==='1');await p.locator('[data-tab="schedule"]').click();await p.locator('#reference-calendar').click();await p.locator('#solve').click();await p.waitForFunction(()=>/Hoàn tất: (FEASIBLE|OPTIMAL)/.test(document.querySelector('#message').textContent));ok('Newreference CP solve independently verifies fixture and frozen grades');
 const before=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),lesson=before.result.lessons[0];await change(lesson.day,lesson.shift,0);await p.reload();await p.waitForFunction(()=>document.querySelector('#nc').textContent==='1');assert((await p.locator('#trust').textContent()).includes('đã cũ'));assert.equal(await input(lesson.day,lesson.shift).inputValue(),'0');await p.locator('#warm').uncheck();await p.locator('#solve').click();await p.locator('#session-confirm').waitFor({state:'visible'});assert((await p.locator('#session-confirm-message').textContent()).includes('tiết đã xếp'));await p.locator('#session-cancel').click();await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('Đã hủy'));let saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.deepEqual(saved.result.lessons,before.result.lessons);ok('Changedcalendar persistsreload; coldsolve still needsconfirmation; cancelpreservesrows');
 await p.locator('#solve').click();await p.locator('#session-confirm').waitFor({state:'visible'});assert(await input(0,'am').isDisabled());await p.locator('#session-continue').click();await p.waitForFunction(()=>/Hoàn tất: (FEASIBLE|OPTIMAL)/.test(document.querySelector('#message').textContent));saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.result.locked_hash_after,before.result.locked_hash_before);assert(!saved.result.lessons.some(l=>l.day===lesson.day&&l.shift===lesson.shift));assert(saved.result.verification.valid);ok('Confirmation startsselectedgradeonly; zero-period and immutablelock verified');
 fs.writeFileSync(R+'/reports/SESSION_ZERO_BACKUP.json',JSON.stringify(saved,null,2));
 // API rejects affected changes without exact token, even if warmstart is disabled.
 const boot=await(await p.request.get(base+'/api/bootstrap')).json(),headers={'X-CSRF-Token':boot.token};const config=structuredClone(saved.config),l=saved.result.lessons[0];config.session_config.week[l.day][l.shift]=0;
 const resp=await p.request.post(base+'/api/solve',{headers,data:{data:saved.data,config,background:saved.background,previous:[],current_schedule:saved.result.lessons}});assert.equal(resp.status(),202);const job=await resp.json();let state;for(;;){state=await(await p.request.get(base+'/api/jobs/'+job.id)).json();if(state.state!=='running')break;await p.waitForTimeout(100);}assert.equal(state.result.status,'BLOCKED');assert(state.result.session_change.confirmation_required);ok('Server blocks unconfirmed affectedschedule before CP');
 for(const [id,fmt] of [['csv','csv'],['export-xlsx','xlsx']]){dl=p.waitForEvent('download');await p.locator('#'+id).click();await(await dl).saveAs(R+'/reports/SESSION_ZERO_EXPORT.'+fmt);}assert(fs.readFileSync(R+'/reports/SESSION_ZERO_EXPORT.csv','utf8').includes('NGHỈ'));ok('Schedule CSV/XLSX exports carry explicit rested sessions');
 await p.locator('#target_grade').selectOption('9');await p.waitForFunction(()=>document.querySelector('#nc').textContent==='1'&&document.querySelector('h1').textContent.includes('9'));saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.result,null);assert.deepEqual(saved.background.config.session_config.class_weeks.C8,configWithClosed(before.config.session_config.week,lesson));ok('Changingfuturegrade freezes exact perclasszero calendar without anygrade9solve');
 assert.deepEqual(errors,[]);ok('No native JavaScript errors');fs.writeFileSync(R+'/reports/SESSION_BROWSER.json',JSON.stringify({status:'PASS',checks,errors},null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
function configWithClosed(week,l){const out=structuredClone(week);out[l.day][l.shift]=0;return out;}
